version: "3"

services:
  ddns:
    container_name: dynu-ddns
    image: chinyongcy/dynuddns:latest
    environment:
      - DYN_HOSTNAME=${DYN_HOSTNAME}
      - DYN_USER=${DYN_USER}
      - DYN_PASS=${DYN_PASS}
      - WAIT_TIME=${WAIT_TIME}
    restart: always